### ISSUE TITLE
Home link on website

### ISSUE THREAD

**Issue by KamalAwasthi** [iiitv/college_website#17]
While I was visiting the new pages created by @singh-pratyush96  and @saurabhjn76 , I realised that there was no home page button or link which could take me back to home page.

I think either we should make a home page link or should make the college logo linked to home page.
Though the home page is not prepared yet but it would work once the page is done.

**Comment by KamalAwasthi** [comment]
I created the issue as per my observation, if the link is already planned to be placed then kindly inform me and close the issue.

**Comment by singhpratyush** [comment]
Make the logo take us home @KamalAwasthi.

**Comment by KamalAwasthi** [comment]
let other members give their opinions too, I will do as per the thing decided then. :blush:

**Comment by aviaryan** [comment]
:+1: for using logo as home link

**Comment by KamalAwasthi** [comment]
Ohk then its decided, College logo will work as link. :+1:

**Comment by ansarimofid** [comment]
i have made college logo and name to link to homepage

**Comment by mayankpi** [comment]
I think it would be a better idea to give a dedicated home button on navigation bar because it would be hard for the new users to guess the logo as the home page link since it is not a usual convention...
