### ISSUE TITLE
Seperate pages for news/announcements/events?

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/college_website#24]

**Comment by singhpratyush** [comment]
My view - single page for all three of them.

**Comment by ansarimofid** [comment]
For now we cannot do it. Later we can do it

**Comment by singhpratyush** [comment]
@ansarimofid if so, then what is the point of mentioning the three separately in the footer?

**Comment by ansarimofid** [comment]
internal links to homepage news, announcements and events

**Comment by ansarimofid** [comment]
footer link has been fixed by internal linking
