### ISSUE TITLE
Empty space in page possibly due to error in div class "wrapper"

### ISSUE THREAD

**Issue by NavneetNandan** [iiitv/college_website#25]
@ansarimofid  kindly check pages like about_us.html and directors_message for empty whitespace.
Possibly there are some wrong values in attributes of css file.

**Comment by NavneetNandan** [comment]
I think in line number 38 of style.css min-height attribute is creating problem.

**Comment by ansarimofid** [comment]
the error was due to wrong closing of tag #20. Fixed
