### ISSUE TITLE
Add mail, phone and map links to header.

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/college_website#33]
Map : `https://mapsengine.google.com/map/edit?mid=z9_cN3Da9QvA.kqu7Eeg9LOsk`  
Mail : `helpdesk@iiitv.ac.in`  
Phone : `(+91) 079-29750281`

**Comment by ansarimofid** [comment]
![iiitv](https://cloud.githubusercontent.com/assets/9111119/15323082/cb76cdc0-1c5d-11e6-80c1-1a6c39a007e3.JPG)
I was thinking of adding popover links refer [link](http://www.w3schools.com/bootstrap/bootstrap_popover.asp). What do you say??

**Comment by singhpratyush** [comment]
As you like it. :+1:

**Comment by arpit1997** [comment]
![screenshot from 2016-05-17 20 12 45](https://cloud.githubusercontent.com/assets/10682054/15326559/22a6af30-1c6c-11e6-8a9a-ab6d986fbb25.png)

@ansarimofid I guess the three options should toggle or only one should be open at a time

**Comment by ansarimofid** [comment]
Toggle has been fixed. Thanks @arpit1997
