### ISSUE TITLE
Popover Issue

### ISSUE THREAD

**Issue by RajuKoushik** [iiitv/college_website#35]
The idea is to show the popover when you click the button and to hide the popover when you click outside the button.
This is would enhance the usability.

**Comment by singhpratyush** [comment]
Clicking outside is not an good idea. People may end up clicking some link in order to hide the popup, getting extremely annoyed in the process.

**Comment by RajuKoushik** [comment]
But this trend is followed in every website, so it should not be a problem.

**Comment by ansarimofid** [comment]
@ I think singh-pratyush96  is right!

**Comment by singhpratyush** [comment]
But the popups do look annoying because you have to click again on them to close. Is there anything we can do?

**Comment by RajuKoushik** [comment]
exactly @singh-pratyush96  thats the reason I have added a js snippet to overcome it.
Its always annoying when the pop over shows up that way.

**Comment by RajuKoushik** [comment]
What do you think @ansarimofid ? Doesn't it look annoying when you have to go back to the icon to disable it?

**Comment by ansarimofid** [comment]
Ya I agree @RajuKoushik .

**Comment by singhpratyush** [comment]
@ansarimofid : Please verify the code in pull request #37 and take proper action.

**Comment by RajuKoushik** [comment]
The thing is it has to be changed for every page. @singh-pratyush96  @ansarimofid

**Comment by ansarimofid** [comment]
Ok i will review

**Comment by ansarimofid** [comment]
I saw your page https://rajukoushik.github.io/college_website/about.html.
It still has issue  refer to  #33 @arpit1997 comment

**Comment by ansarimofid** [comment]
and why don't you use class instead of using id for each link.

**Comment by RajuKoushik** [comment]
@ansarimofid  I have updated the code with a new pull requests which does not have such issues(regarding #33rd issue) and using js classes. You can review it now.

**Comment by ansarimofid** [comment]
great work @RajuKoushik . Now you have great task of updating all the pages with the code of popover.

**Comment by singhpratyush** [comment]
We have to look @ #40 now for things related to popover. Closing.

**Comment by mayankpi** [comment]
But the chances of clicking on any other link is very less (i.e. when the user knows very little about the browsing) but it is more annoying when it always shows until you click the tiny icon on the page.
