### ISSUE TITLE
Use a static site generator ?

### ISSUE THREAD

**Issue by aviaryan** [iiitv/college_website#4]
As there are about 20-25 pages and lots of pages in them will have a common design scheme, I suggest using a static site generator for automation of page generation.

I suggest [pelican](http://docs.getpelican.com/) because it is written in Python which most of the collaborators are aware of. 

Once a pelican or other site-gen project is setup on the master branch, we can use TravisCI for auto-pushing the build site to gh-pages.

**Comment by singhpratyush** [comment]
According to me, we need not to use it here. Our primary goal is to build a running static website before 18 May. 25 is not such big number and old school copy paste techniques would do great.

**Comment by singhpratyush** [comment]
@ansarimofid @KamalAwasthi @mayankpi @navneet8 Any views?

**Comment by saurabhjn76** [comment]
Considering the deadline ,copy paste would be good.

**Comment by NavneetNandan** [comment]
I think this work can be done by copy paste. As we have many collaborators, we can easily distribute pages to work on, if a layout is decided for such type of pages.

**Comment by KamalAwasthi** [comment]
Yes! I would like to go with @singh-pratyush96 . Some minor changes in the code for each page would do the work. And we have many collaborators hence the number of pages should not matter.

**Comment by aviaryan** [comment]
Done then, we are not using a static site generator. Once the layouts are made, individual content pages can be created.
