### ISSUE TITLE
Update new popover code to each page

### ISSUE THREAD

**Issue by ansarimofid** [iiitv/college_website#40]
There are 20 pages waiting to get updated,
Update and send PR

**Comment by RajuKoushik** [comment]
@ansarimofid  Man I need to send a Pull request for around 20 times, instead give me the access. I think it should not be a problem I guess @ansarimofid

**Comment by singhpratyush** [comment]
Access granted @RajuKoushik

**Comment by ansarimofid** [comment]
@RajuKoushik  you can edit all the pages with single commit else it would mean 20 unnecessary commits.

**Comment by ansarimofid** [comment]
Like you did 4 commit to update single page

**Comment by RajuKoushik** [comment]
I don't have a proper editor to do that for now.

**Comment by RajuKoushik** [comment]
I am actually directly editing it on github itself.

**Comment by ansarimofid** [comment]
It's better you leave it then. @saurabhjn76  may do this

**Comment by ansarimofid** [comment]
@saurabhjn76  Refer to  PR #39 for more information

**Comment by RajuKoushik** [comment]
This has to be closed now. Every page has been updated.

**Comment by ansarimofid** [comment]
@RajuKoushik  I think you missed pages of linkage folder and index.html
