### ISSUE TITLE
moodle link

### ISSUE THREAD

**Issue by harishkrupo** [iiitv/college_website#41]
The moodle server's address is moodle.iiitv.ac.in not moodle.iiitvadodara.ac.in
Please change it

**Comment by ansarimofid** [comment]
@saurabhjn76 You forgot to edit the files inlinkage folder

**Comment by saurabhjn76** [comment]
OOPS !!
:smile: will do this now.

**Comment by harishkrupo** [comment]
Closed

**Comment by harishkrupo** [comment]
:+1:
