### ISSUE TITLE
Main page image view

### ISSUE THREAD

**Issue by harishkrupo** [iiitv/college_website#42]
The image view in the first page has a lot of empty space before and after the image. 
Suggestion: You can use a horizontal scroll view and place the images in it so as to fill up the empty space

**Comment by ansarimofid** [comment]
You are absolutely right about images. We needed high resolution images for homepage so that there won't be any extra spaces but college authority provided us low res. Images.

**Comment by harishkrupo** [comment]
So that's why I suggested using a scroll view.
This would also be helpful if the page is opened on a touch device.
Because scrolling is natural and intuitive on a touch screen

**Comment by harishkrupo** [comment]
So my idea is something like this:
The image in the center will be complete but the images on the sides will be cut in half (or proportionately).

**Comment by ansarimofid** [comment]
OK I got it

**Comment by harishkrupo** [comment]
![scroll](https://cloud.githubusercontent.com/assets/10773883/15348867/c0aab42c-1ceb-11e6-9baf-172ad33d162a.png)

This is what I am talking about. It would be great if you can do something like this.

**Comment by ansarimofid** [comment]
Yes. I got the idea

**Comment by singhpratyush** [comment]
The new design added by @ansarimofid closes the issue.

**Comment by harishkrupo** [comment]
The view is great. Awesome, good job! :+1
