### ISSUE TITLE
Visited links color

### ISSUE THREAD

**Issue by ShalineeSingh** [iiitv/college_website#46]
To maintain the uniformity of the website, I would suggest you change the color of the visited links to the shade of green that you have used everywhere else.

**Comment by singhpratyush** [comment]
@ansarimofid : Views?

**Comment by ansarimofid** [comment]
I'm afraid we may not use the primary color of the site for visited links. May look for other alternatives.

**Comment by singhpratyush** [comment]
@ansarimofid : Any updates on the issue?
