### ISSUE TITLE
PG admissions page

### ISSUE THREAD

**Issue by ShalineeSingh** [iiitv/college_website#47]
Admissions> phd... Headers are not visible in this page and also the footer is not like the other pages.

**Comment by singhpratyush** [comment]
The page redirects immediately [here](http://pgadmissions.iiitvadodara.ac.in/phdapplications) (which is a part of Google Sites created previously by institute) and is not included in this repository.

**Comment by ShalineeSingh** [comment]
This is just a simple text page. You can create your own page for that. It will be a better option.

**Comment by ansarimofid** [comment]
First we want the website to be approved by college authority and then we can include all sort of other things. Currently we are concentrating on basic things.
