### ISSUE TITLE
The website could be written more Effectively and Consistently.

### ISSUE THREAD

**Issue by RajuKoushik** [iiitv/college_website#54]
Every time a new page is created the whole basic layout is copied and then pasted. Instead if a single template is created with all the attributes and included or inserted in every web page this could be more helpful. If some change has to be made in the template then we don't have to edit the HTML code of each and every page if such template is made and inserted.

**Comment by ansarimofid** [comment]
Yes, we were well aware of this fact and there was discussion too related to this #4 .
