### ISSUE TITLE
Pop ups of the address, phone no. and email should disappear by clicking anywhere on the page not just the icons.

### ISSUE THREAD

**Issue by mayankpi** [iiitv/college_website#55]

**Comment by saurabhjn76** [comment]
Please refer to issue #35 .

**Comment by ansarimofid** [comment]
its already done by @RajuKoushik . But he left few pages index.html and linkages files by mistake

**Comment by mayankpi** [comment]
But the chances of clicking on any other link is very less (i.e. when the user knows very little about the browsing) but it is more annoying when it always shows until you click the tiny icon on the page.
