### ISSUE TITLE
Drop down menu of the navigation bar disappears after clicking.

### ISSUE THREAD

**Issue by mayankpi** [iiitv/college_website#56]
e.g.
drop down menu disappears when we click 'B.Tech' in the 'Academics' in navigation bar, but it should not...

**Comment by ansarimofid** [comment]
The drop down effect on academics get activated on hover. Its alright in desktop but it creates problem in touch devices where there is nothing like hover effect. That's why it is happening. It would be great help @mayankpi  if you can find any way to deal with this

**Comment by mayankpi** [comment]
It may be fixed if we make it active on click also and not just by hovering...

**Comment by singhpratyush** [comment]
As @ansarimofid mentioned, it will create problems in touch devices.
